services:
  - type: web
    name: imf-gadget-api
    env: node
    buildCommand: |
      apk add --no-cache openssl
      npm ci
      npx prisma generate
    startCommand: >-
      npx prisma db push --accept-data-loss && 
      npm start
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: imf_gadgets
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
    plan: free
    autoDeploy: true

databases:
  - name: imf_gadgets
    databaseName: imfgadget
    user: imfgadget
    plan: free
